package mariani.problem1_50;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem2 {

	private static final int calc(final int max) {
		int sum = 2;
		int first = 1;
		int second = 2;
		int next = 0;
		while (next < max) {
			if ((next % 2 == 0)) {
				sum += next;
			}
			next = first + second;
			first = second;
			second = next;
		}
		return sum;
	}
	
	public static final int calc() {
//		return calc(10); // answer --> 10
//		return calc(40); // answer --> 44
		return calc(4000000); // answer --> 4613732
	}

}
